### ISSUE TITLE
Cannot Read TeamID from undefined

### ISSUE THREAD

**Issue by Swiftzn** [darksteel88/LeagueRankedScript#9]
Hi There, 

i am getting the following error

TypeError: Cannot read property "teamid" from Undefined.

I am on the EUW Server so not sure if it is only a problem experienced on EUW

Great project btw

**Comment by darksteel88** [comment]
Can you tell me what your summoner name is? I'm going to run it myself and investigate.

**Comment by Swiftzn** [comment]
My summoner name is swiftzn

**Comment by darksteel88** [comment]
Did you populate any data or does this happen right away? I configured a sheet for your account and I haven't had any problems loading the data. 

If it's happening and your sheet doesn't populate any data at all, then I think you may have configured it incorrectly. If it's happening on just some particular match and your sheet populated a bunch of other rows, what is the match id for the row that fails?

**Comment by Swiftzn** [comment]
I made a copy of your sheet as per read me then i put my summoner name all
lowercase then i change season to be only 2016 then i click run

It fails on the first game though it does populate some parts i have
attached screenshots of how far it gets

http://imgur.com/a/fkgpC

I think i just realised what it could be, the API_Key i am using is a Dev
one so it is limited to ten calls every 10 Seconds would this be causing a
problem?

**Comment by darksteel88** [comment]
You can fix that if you change it to Swiftzn, there will be a proper solution to that issue soon.
